approve:
- commandHelpLink: ""
  repos:
  - redhat-appstudio/rhtap-e2e
  require_self_approval: false
external_plugins:
  redhat-appstudio/rhtap-e2e:
  - endpoint: http://refresh
    events:
    - issue_comment
    name: refresh
  - endpoint: http://cherrypick
    events:
    - issue_comment
    - pull_request
    name: cherrypick
  - endpoint: http://needs-rebase
    events:
    - issue_comment
    - pull_request
    name: needs-rebase
  - endpoint: http://backport-verifier
    events:
    - issue_comment
    - pull_request
    name: backport-verifier
  - endpoint: http://payload-testing-prow-plugin
    events:
    - issue_comment
    name: payload-testing-prow-plugin
lgtm:
- repos:
  - redhat-appstudio/rhtap-e2e
  review_acts_as_lgtm: true
plugins:
  redhat-appstudio/rhtap-e2e:
    plugins:
    - assign
    - blunderbuss
    - cat
    - dog
    - heart
    - golint
    - goose
    - help
    - hold
    - jira
    - label
    - lgtm
    - lifecycle
    - override
    - pony
    - retitle
    - shrug
    - sigmention
    - skip
    - trigger
    - verify-owners
    - owners-label
    - wip
    - yuks
    - approve
