build_root:
  project_image:
    dockerfile_path: ci/Dockerfile
images:
- dockerfile_path: ci/Dockerfile
  from: src
  to: rhtap-e2e-tests
promotion:
  to:
  - name: redhat-appstudio
    namespace: ci
releases:
  latest:
    release:
      architecture: amd64
      channel: fast
      version: "4.14"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: rhtap-e2e-presubmit
  cluster_claim:
    architecture: amd64
    cloud: aws
    labels:
      region: us-east-2
    owner: rhtap
    product: ocp
    timeout: 1h0m0s
    version: "4.14"
  postsubmit: true
  skip_if_only_changed: ^docs/|^\.github/|^\.tekton/|\.md$|^tests/release/pipelines/|^tests/load-tests/|^cmd/loadTests.go$|^(?:.*/)?(?:\.gitignore|OWNERS|OWNERS_ALIASES|PROJECT|LICENSE)$
  steps:
    env:
      RHTAP_ENABLE_TPA: "false"
    test:
    - ref: redhat-appstudio-rhtap-e2e-e2e-test
    workflow: redhat-appstudio-rhtap-e2e
zz_generated_metadata:
  branch: main
  org: redhat-appstudio
  repo: rhtap-e2e
